permissions:
  contents: write
name: Déploiement du site sur GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master' selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Récupération du code source
      - name: Récupération du code source
        uses: actions/checkout@v3

      # Préparation du contenu du site
      - name: Préparer le contenu du site
        run: |
          mkdir -p public
          cp -r index.html dashboard.html submit.html style.css maquette_stitch.png README.md public/

      # Déploiement automatique sur GitHub Pages
      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
